[package]
name = "RGM"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.22"
nvml-wrapper = "0.9"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
