[package]
name = "RGM"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.32.0"
egui_plot = "0.33.0"
nvml-wrapper = "0.11.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

crossbeam-channel = "0.5"
